name: flutter_theme_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Manrope
    fonts:
    - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
      weight: 800
    - asset: assets/fonts/manrope/Manrope-Bold.ttf
      weight: 700
    - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/manrope/Manrope-Medium.ttf
      weight: 500
    - asset: assets/fonts/manrope/Manrope-Regular.ttf
      weight: 400
    - asset: assets/fonts/manrope/Manrope-Light.ttf
      weight: 300
    - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
      weight: 200
